[package]
name = "procspawn"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>", "Manish Goregaokar <manishsmail@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[features]
default = ["backtrace"]

[dependencies]
ipc-channel = "0.13.0"
serde = { version = "1.0.104", features = ["derive"] }
backtrace = { version = "0.3.43", optional = true, features = ["serde"] }
